R#:
  type: programming
  color: "#4D266E"
  extensions:
    - ".rsl"
    - ".rsh"
    - ".rss"
    - ".rsp"
    - ".rslib"
  filenames: []
  interpreters:
    - rsc
    - rsrun
  tm_scope: source.rust
  ace_mode: rust
  language_id: 999001
  aliases:
    - rsharp
    - r-sharp
    
